language: node_js
node_js:
  - node
  - lts/*
after_success:
  - test `node --version | cut -c 2,3` -eq 10 && nyc report --reporter=text-lcov | npx coveralls
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
