sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '8'
after_success:
  - npm run coverage
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
