name: Test

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - reopened
    - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - uses: pnpm/action-setup@v2
        with:
          version: '>=6'
          run_install: |
            - args: [--frozen-lockfile, --no-verify-store-integrity]
      - run: npm test
